apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    name: basic-web-srv
    env:  dev
    version: v1
spec:
  containers:
  - name: web-server-ctr
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
