apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app: nginx  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      env: dev
  template:
    metadata:
      labels:
        app: nginx
        env: dev
        version: v1.0
    spec:
      containers:
      - name: my-nginx-alpine-container
        image: nginx:alpine
        livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 2
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
