apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-web-server
  labels:
    app: nginx  
spec:
  replicas: 4
  minReadySeconds: 1 
  progressDeadlineSeconds: 60 
  revisionHistoryLimit: 5  
  strategy:
    type: RollingUpdate # Default method
    rollingUpdate:
      maxSurge: 1  
      maxUnavailable: 1 
  selector:
    matchLabels:
      app: nginx
      env: dev
  template:
    metadata:
      labels:
        app: nginx
        env: dev
        version: v1.0
    spec:
      containers:
      - name: my-nginx-alpine-container
        image:  httpd:2.4-alpine #nginx:1.16-alpine
        livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 2
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
    env: dev
  ports:
    - port: 80
      targetPort: 80